x-server-config: &server-config
    PORT: 3000
    TEST_URL: http://localhost:3000
    DATABASE_URL: postgresql://postgres:secret@database:5432/local
    SUPER_ADMIN_EMAIL: dev@admin.com
    SUPER_ADMIN_PASSWORD: secret
    JWT_SECRET: change_this_often
    ENABLE_SWAGGER: 0
    ENABLE_DEBUG: 0

services:
    database:
        image: postgres:14
        container_name: database
        command: -c 'max_connections=500'
        ports:
            - 5432:5432
        volumes:
            - ./postgres/dumps:/dumps
            # - ./postgres/dumps/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
        working_dir: /scripts
        environment:
            POSTGRES_DB: local
            POSTGRES_PASSWORD: secret
        healthcheck:
            test: pg_isready -d local -U postgres -h 127.0.0.1
            interval: 1s

    server:
        image: local/server
        container_name: api-server
        command: sh -c "npm run knex:migrate && npm run api:prod"
        depends_on:
            - database
        environment:
            <<: *server-config
        volumes:
            - ./jest-stare:/app/jest-stare
